title: Emacsmirror
author: Jonas Bernoulli
email: jonas@bernoul.li
url: https://emacsmirror.org

baseurl: ""
permalink: /:year/:month/:day/:title/index.html
markdown: kramdown
exclude:
  - Makefile
  - assets/emacsmirror.jpg
  - assets/emacsmirror.xcf
